

import GlassPanel from "./ui/GlassPanel";
import SectionTitle from "./ui/SectionTitle";

function BusinessImpact({ sensor, result }) {
  const risk = result?.final_risk ?? "SAFE";

  const preventedIncidents =
    risk === "CRITICAL" ? 1 : 0;

  const permitsBlocked =
    risk === "CRITICAL"
      ? 2
      : risk === "HIGH"
        ? 1
        : 0;

  const workersProtected =
    risk === "CRITICAL"
      ? 4
      : risk === "HIGH"
        ? 3
        : 1;

  const estimatedSavings =
    risk === "CRITICAL"
      ? "₹18.4 Crore"
      : risk === "HIGH"
        ? "₹7.2 Crore"
        : "₹0";


  const cards = [
    {
      title: "🛡 Workers Protected",
      value: workersProtected,
      color: "#22c55e",
    },
    {
      title: "🚫 Permits Blocked",
      value: permitsBlocked,
      color: "#f97316",
    },
    {
      title: "⚠ Incidents Prevented",
      value: preventedIncidents,
      color: "#ef4444",
    },
    {
      title: "💰 Estimated Loss Avoided",
      value: estimatedSavings,
      color: "#38bdf8",
    },
  ];

  return (
    <GlassPanel>
      <SectionTitle
        title="📈 Business Impact"
        subtitle="Real-time operational value generated by SentinelAI"
      />

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
          gap: "12px",
        }}
      >
        {cards.map((card, index) => (
          <div
            key={index}
            style={{
              background: "#111827",
              borderRadius: "10px",
              padding: "12px",
              borderLeft: `4px solid ${card.color}`,
              transition: "all .25s ease",
              cursor: "default",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.transform = "translateY(-2px)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = "translateY(0)";
            }}
          >
            <div
              style={{
                color: "#94A3B8",
                fontSize: "12px",
                fontWeight: "500",
                lineHeight: 1.4,
              }}
            >
              {card.title}
            </div>

            <div
              style={{
                marginTop: "8px",
                color: card.color,
                fontSize: "24px",
                fontWeight: "700",
                letterSpacing: "0.3px",
              }}
            >
              {card.value}
            </div>
          </div>
        ))}
      </div>
    </GlassPanel>
  );
}

export default BusinessImpact;