from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

styles = getSampleStyleSheet()

def generate_report(sensor, decision):

    pdf = SimpleDocTemplate("reports/incident_report.pdf")

    story = []

    story.append(Paragraph("<b>Industrial Safety Incident Report</b>", styles["Title"]))
    story.append(Paragraph("<b>Sensor Readings</b>",styles["Heading2"]))

    story.append(Paragraph(f"Gas Concentration : {sensor['gas']} ppm",styles["BodyText"]))
    story.append(Paragraph(f"Temperature : {sensor['temperature']} °C",styles["BodyText"]))
    story.append(Paragraph(f"Pressure : {sensor['pressure']} kPa",styles["BodyText"]))
    story.append(Paragraph("<br/><b>AI Risk Assessment</b>",styles["Heading2"]))
    story.append(Paragraph("Risk Level : HIGH",styles["BodyText"]))
    story.append(Paragraph("Worker Zone : Boiler Area",styles["BodyText"]))
    story.append(Paragraph("Permit : Hot Work",styles["BodyText"]))
    story.append(Paragraph("PPE : Helmet Missing",styles["BodyText"]))
    story.append(Paragraph("Generated By : SentinelAI",styles["BodyText"]))
    story.append(Paragraph("<br/><b>AI Decision</b>", styles["Heading2"]))
    story.append(Paragraph(decision.replace("\n", "<br/>"), styles["BodyText"]))

    pdf.build(story)

    return "Incident Report Generated"